DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
author = "umatare5"
baseURL = "https://dives.dev"
canonifyurls = true
hasCJKLanguage = true
languageCode = "en-us"
metaDataFormat = "yaml"
theme = "blist"
title = "My Logbook"

[languages]
[languages.en]
contentDir = "content/en" #English
languageName = "English" 
weight = 1 
[languages.en.params]
introPhoto = "/me-128x128.png"
introSubtitle = "This is a logbook records my scuba divings."
introTitle = "Hi 👋 I'm umatare5"

[[languages.en.menu.main]]
name = "Divelogs"
url = "blog"
weight = 1

[[languages.en.menu.main]]
name = "Overview"
url = "overview"
weight = 2

[[languages.en.menu.main]]
name = "Equipments"
url = "equipments"
weight = 3

[[languages.en.menu.main]]
name = "About"
url = "about"
weight = 4

[params]
# Enable the darkmode toggle in header
darkModeToggle = true

# Enable search in header
enableSearch = true

# Custom copyright - optional
copyright = "Copyright © 2022 - umatare5 and Katheryn Fox · All rights reserved"
favicon = "/favicon.svg"

# Color for the intro details and social links block, not applicable for dark mode
# Supported values: Any color from TailwindCSS default colors
# Reference: https://tailwindcss.com/docs/customizing-colors
ascentColor = "bg-blue-100"

[params.homepage.social]
# Global params common for both languages
description = "Repos related to this page and travel memories"
github = "https://github.com/umatare5"
instagram = "https://www.instagram.com/um1vva1120"
title = "Links"

[[menu.main]]
name = "About"
url = "/about"

[build]
writeStats = true

[outputs]
home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
